services:
  app:
    build: .
    volumes:
      - .:/app     # monta o código local dentro do container
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev
